// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CSF
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Data : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static Data GetRootAsData(ByteBuffer _bb) { return GetRootAsData(_bb, new Data()); }
  public static Data GetRootAsData(ByteBuffer _bb, Data obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Data __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int FlyingToIndex { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public CSF.Entry? Flightplan(int j) { int o = __p.__offset(6); return o != 0 ? (CSF.Entry?)(new CSF.Entry()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int FlightplanLength { get { int o = __p.__offset(6); return o != 0 ? __p.__vector_len(o) : 0; } }
  public CSF.Holding_Fix? HoldingFix { get { int o = __p.__offset(8); return o != 0 ? (CSF.Holding_Fix?)(new CSF.Holding_Fix()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<CSF.Data> CreateData(FlatBufferBuilder builder,
      int flying_to_index = 0,
      VectorOffset flightplanOffset = default(VectorOffset),
      Offset<CSF.Holding_Fix> holding_fixOffset = default(Offset<CSF.Holding_Fix>)) {
    builder.StartTable(3);
    Data.AddHoldingFix(builder, holding_fixOffset);
    Data.AddFlightplan(builder, flightplanOffset);
    Data.AddFlyingToIndex(builder, flying_to_index);
    return Data.EndData(builder);
  }

  public static void StartData(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddFlyingToIndex(FlatBufferBuilder builder, int flyingToIndex) { builder.AddInt(0, flyingToIndex, 0); }
  public static void AddFlightplan(FlatBufferBuilder builder, VectorOffset flightplanOffset) { builder.AddOffset(1, flightplanOffset.Value, 0); }
  public static VectorOffset CreateFlightplanVector(FlatBufferBuilder builder, Offset<CSF.Entry>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateFlightplanVectorBlock(FlatBufferBuilder builder, Offset<CSF.Entry>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartFlightplanVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddHoldingFix(FlatBufferBuilder builder, Offset<CSF.Holding_Fix> holdingFixOffset) { builder.AddOffset(2, holdingFixOffset.Value, 0); }
  public static Offset<CSF.Data> EndData(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CSF.Data>(o);
  }
  public static void FinishDataBuffer(FlatBufferBuilder builder, Offset<CSF.Data> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedDataBuffer(FlatBufferBuilder builder, Offset<CSF.Data> offset) { builder.FinishSizePrefixed(offset.Value); }
};


}
