// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CSF
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Entry : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static Entry GetRootAsEntry(ByteBuffer _bb) { return GetRootAsEntry(_bb, new Entry()); }
  public static Entry GetRootAsEntry(ByteBuffer _bb, Entry obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Entry __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Type { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public string Name { get { int o = __p.__offset(6); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(6, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(6); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(6); }
  public float Latitude { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Longitude { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int Altitude { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<CSF.Entry> CreateEntry(FlatBufferBuilder builder,
      int type = 0,
      StringOffset nameOffset = default(StringOffset),
      float latitude = 0.0f,
      float longitude = 0.0f,
      int altitude = 0) {
    builder.StartTable(5);
    Entry.AddAltitude(builder, altitude);
    Entry.AddLongitude(builder, longitude);
    Entry.AddLatitude(builder, latitude);
    Entry.AddName(builder, nameOffset);
    Entry.AddType(builder, type);
    return Entry.EndEntry(builder);
  }

  public static void StartEntry(FlatBufferBuilder builder) { builder.StartTable(5); }
  public static void AddType(FlatBufferBuilder builder, int type) { builder.AddInt(0, type, 0); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(1, nameOffset.Value, 0); }
  public static void AddLatitude(FlatBufferBuilder builder, float latitude) { builder.AddFloat(2, latitude, 0.0f); }
  public static void AddLongitude(FlatBufferBuilder builder, float longitude) { builder.AddFloat(3, longitude, 0.0f); }
  public static void AddAltitude(FlatBufferBuilder builder, int altitude) { builder.AddInt(4, altitude, 0); }
  public static Offset<CSF.Entry> EndEntry(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CSF.Entry>(o);
  }
};


}
