// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace CSF
{

using global::System;
using global::System.Collections.Generic;
using global::FlatBuffers;

public struct Holding_Fix : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_1_12_0(); }
  public static Holding_Fix GetRootAsHolding_Fix(ByteBuffer _bb) { return GetRootAsHolding_Fix(_bb, new Holding_Fix()); }
  public static Holding_Fix GetRootAsHolding_Fix(ByteBuffer _bb, Holding_Fix obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public Holding_Fix __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public string Name { get { int o = __p.__offset(4); return o != 0 ? __p.__string(o + __p.bb_pos) : null; } }
#if ENABLE_SPAN_T
  public Span<byte> GetNameBytes() { return __p.__vector_as_span<byte>(4, 1); }
#else
  public ArraySegment<byte>? GetNameBytes() { return __p.__vector_as_arraysegment(4); }
#endif
  public byte[] GetNameArray() { return __p.__vector_as_array<byte>(4); }
  public float Course { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public int TurnDirection { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public float LegDistance { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Latitude { get { int o = __p.__offset(12); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float Longitude { get { int o = __p.__offset(14); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float HoldSpeed { get { int o = __p.__offset(16); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float HoldTurnAngle { get { int o = __p.__offset(18); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }
  public float HoldTurnRadius { get { int o = __p.__offset(20); return o != 0 ? __p.bb.GetFloat(o + __p.bb_pos) : (float)0.0f; } }

  public static Offset<CSF.Holding_Fix> CreateHolding_Fix(FlatBufferBuilder builder,
      StringOffset nameOffset = default(StringOffset),
      float course = 0.0f,
      int turn_direction = 0,
      float leg_distance = 0.0f,
      float latitude = 0.0f,
      float longitude = 0.0f,
      float hold_speed = 0.0f,
      float hold_turn_angle = 0.0f,
      float hold_turn_radius = 0.0f) {
    builder.StartTable(9);
    Holding_Fix.AddHoldTurnRadius(builder, hold_turn_radius);
    Holding_Fix.AddHoldTurnAngle(builder, hold_turn_angle);
    Holding_Fix.AddHoldSpeed(builder, hold_speed);
    Holding_Fix.AddLongitude(builder, longitude);
    Holding_Fix.AddLatitude(builder, latitude);
    Holding_Fix.AddLegDistance(builder, leg_distance);
    Holding_Fix.AddTurnDirection(builder, turn_direction);
    Holding_Fix.AddCourse(builder, course);
    Holding_Fix.AddName(builder, nameOffset);
    return Holding_Fix.EndHolding_Fix(builder);
  }

  public static void StartHolding_Fix(FlatBufferBuilder builder) { builder.StartTable(9); }
  public static void AddName(FlatBufferBuilder builder, StringOffset nameOffset) { builder.AddOffset(0, nameOffset.Value, 0); }
  public static void AddCourse(FlatBufferBuilder builder, float course) { builder.AddFloat(1, course, 0.0f); }
  public static void AddTurnDirection(FlatBufferBuilder builder, int turnDirection) { builder.AddInt(2, turnDirection, 0); }
  public static void AddLegDistance(FlatBufferBuilder builder, float legDistance) { builder.AddFloat(3, legDistance, 0.0f); }
  public static void AddLatitude(FlatBufferBuilder builder, float latitude) { builder.AddFloat(4, latitude, 0.0f); }
  public static void AddLongitude(FlatBufferBuilder builder, float longitude) { builder.AddFloat(5, longitude, 0.0f); }
  public static void AddHoldSpeed(FlatBufferBuilder builder, float holdSpeed) { builder.AddFloat(6, holdSpeed, 0.0f); }
  public static void AddHoldTurnAngle(FlatBufferBuilder builder, float holdTurnAngle) { builder.AddFloat(7, holdTurnAngle, 0.0f); }
  public static void AddHoldTurnRadius(FlatBufferBuilder builder, float holdTurnRadius) { builder.AddFloat(8, holdTurnRadius, 0.0f); }
  public static Offset<CSF.Holding_Fix> EndHolding_Fix(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<CSF.Holding_Fix>(o);
  }
};


}
